service:
  name: thedecidermachine

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  environment:
    SQS_URL: !Ref RestaurantUrlQueue
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:GetQueueUrl
        - sqs:GetQueueAttributes
        - sqs:DeleteMessage
        - sqs:ChangeMessageVisibility
      Resource: !GetAtt RestaurantUrlQueue.Arn

functions:
  scrapeRestaurantDetails:
    handler: src/detailScraper/handler.scrape
    events:
      - sqs:
          arn: !GetAtt RestaurantUrlQueue.Arn
  scrapeRestaurantUrls:
    handler: src/scraper/handler.scrape
    timeout: 60

resources:
  Resources:
    RestaurantUrlQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service.name}-queue
