service:
  name: thedecidermachine

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  environment:
    SQS_URL: !Ref RestaurantUrlQueue
    REGION: ${self:provider.region}
    DYNAMODB_RESTAURANT_TABLE: ${self:service.name}-db
    DYNAMODB_ADDRESS_TABLE: ${self:service.name}-address-db
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:GetQueueUrl
        - sqs:GetQueueAttributes
        - sqs:DeleteMessage
        - sqs:ChangeMessageVisibility
      Resource: !GetAtt RestaurantUrlQueue.Arn
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
      - !GetAtt RestaurantMenuDatabase.Arn
      - !GetAtt RestaurantAddressDatabase.Arn

functions:
  scrapeRestaurantDetails:
    handler: src/detailScraper/handler.scrape
    timeout: 30
    events:
      - sqs:
          arn: !GetAtt RestaurantUrlQueue.Arn
          batchSize: 10
  scrapeRestaurantUrls:
    handler: src/scraper/handler.scrape
    timeout: 60
    events:
      - schedule:
        rate: cron(0 7 * * * *)
        enabled: true


resources:
  Resources:
    RestaurantUrlQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service.name}-queue
    RestaurantMenuDatabase:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: restaurantName
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: restaurantName
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        TableName: ${self:service.name}-db
    RestaurantAddressDatabase:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: address
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: address
            KeyType: HASH
        TableName: ${self:service.name}-address-db